[build]
  functions = "./functions"
  command = "yarn build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/umi.css"
  to = "/dist/umi.css"
  status = 200

[[redirects]]
  from = "/umi.js"
  to = "/dist/umi.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/dist/index.html"
  status = 200