[build]
  functions = "./functions"
  command = "yarn build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
    
[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200